### ISSUE TITLE
Run without Docker

### ISSUE THREAD

**Issue by hoanghng** [avolkov1/multinode_containers#1]
I'd like to run Horovod + Pytorch without Docker because it's not installed in my lab's system and I don't `sudo` permission to do that.

**Comment by avolkov1** [comment]
This repo is specifically to demonstrate containerized runs. If docker is not allowed in your lab cluster you could use singularity which does not require sudo. Creating containers does typically require elevated privileges. You need to create/prep singularity containers prior to running. Typically labs provide a sandboxed system with elevated privileges where you would prepare containers and stage the containers to clusters where you want to run the jobs.
